---
#global settings
global:
  scrape_interval: 15s
  # scrape_timeout: 10s
  evaluation_interval: 15s

#alerting settings
# alerting:
#   alertmanagers:
#   - static_configs:
#     - target:
    # - alertmanager: 9093

# rule settings
rule_files:
  - "first_rule.yml/rules"
  - "second_rules.yml/.rules"

# scrape config
# metrics or the exporters that we require to get pulled
scrape_configs:
  - job_name: 'test_exporter_1'
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    scrape_interval: 30s
    static_configs:
    - targets:
      - "test_app_2:5000"
  - job_name: 'test_exporter_2'
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    scrape_interval: 30s
    static_configs:
    - targets:
      - "localhost:5000"

